name: 🧩 Feature
description: 새로운 기능 추가 또는 제품 가치에 직접적인 영향을 주는 기능 개발
title: "[feature] "
labels: ["feature"]
assignees:
  - octocat
type: feature
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 추가 또는 제품 가치에 직접적인 영향을 주는 기능 개발

  - type: input
    id: overview
    attributes:
      label: 기능 개요
      description: 이 작업의 목적 또는 배경
      placeholder: |
        - 새로운 API 추가
        - 신규 UI 화면 또는 워크플로우
        - 완전히 새로운 기능 영역
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 내용
      description: |
        - 체크리스트 또는 간단한 작업 설명
        - 반드시 체크리스트로 작성하지 않아도 됨 
        - 자유롭게 작업내용을 간략하게 작성
        - 하위 태스크가 있다면 생략 가능
      placeholder: |
        - [ ] 체크리스트 
        - 자유로운 작업 설명
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 참고
      description: |
        - 상위 이슈 또는 참조 링크
        - 노션 관련 링크(분석, 설계 등)
        - 스크린샷
    validations:
      required: false
