name: "🐞 Bugfix"
description: "예기치 않은 오류나 잘못된 동작을 수정하는 작업 "
labels: ["bugfix"]

body:
  - type: markdown
    attributes:
      value: |
        ```Bugfix``` 예기치 않은 오류나 잘못된 동작을 수정하는 작업
  - type: textarea
    id: Description
    attributes:
      label: Add a description
      placeholder: "Bugfix"
      value: |
        ## 문제 상황
        발생한 오류 설명
        
        ## 재현 방법
        1.
        2.
        3.
        
        ## 기대 동작
        정상적으로 동작해야 하는 방식
        
        ## 작업 내용
        - 반드시 체크리스트로 작성하지 않아도 됨
        - 자유롭게 작업내용을 간략하게 작성
        - 하위 태스크가 있다면 생략 가능
        - [ ] 작업 항목
        - [ ] 작업 항목
    validations:
      required: true
