name: "🧹 Chore"
description: "기능 변경 없이 프로젝트 운영·유지를 위한 작업"
labels: ["chore"]
type: chore

body:
  - type: markdown
    attributes:
      value: |
        ```Chore``` 기능 변경 없이 프로젝트 운영·유지를 위한 작업
  - type: textarea
    id: Description
    attributes:
      label: Add a description
      placeholder: "Chore"
      value: |
        ## 작업 내용
        - 문서 수정
        - 설정 변경
        - 의존성 업데이트
        - 폴더 구조 정리
    validations:
      required: true
