name: "🧹 Research"
description: "의사결정을 위한 조사, 벤치마킹, 기술 검증(PoC)"
labels: ["research"]
type: research

body:
  - type: markdown
    attributes:
      value: |
        ```Research``` 의사결정을 위한 조사, 벤치마킹, 기술 검증(PoC)
  - type: textarea
    id: Description
    attributes:
      label: Add a description
      placeholder: "Research"
      value: |
        ## 조사 목적
        무엇을 알아보기 위한 조사인지 목적 기술

        ## 조사 내용
        - 조사 항목

        ## 결과 정리
        - 조사 결과 또는 결론
        - 노션 문서 링크(선택)
    validations:
      required: true
