name: "🛠 Feature"
description: "Feature / Enhancement / Bugfix 등을 구성하는 하위 작업"
title: "[Feature] "
labels: ["Feature"]
body:
  - type: textarea
    id: tasks
    attributes:
      label: 작업 내용
      description: 수행할 작업을 작성해 주세요.
      placeholder: |
        - [ ] API 구현
        - [ ] 설정 분리
        - [ ] 테스트 코드 작성
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고
      description: 상위 이슈 또는 참고 링크를 작성해 주세요.
      placeholder: |
        - 예) 상위 이슈 #123
        - 예) 노션 링크
    validations:
      required: false
